### ISSUE TITLE
unable to setup using vault 1.12.2

### ISSUE THREAD

**Issue by datagen24** [1Password/vault-plugin-secrets-onepassword#26]
following the instructions I get vault API errors indicating a library is out of date

the SDK version has reved substantially from the one used in the go.mod file from 0.1.12 (released Jul 25, 2019) to 0.7.0 (released Jan 13, 2023)
I have been testing and I have been able to build with the SDK up 0.3.0 but I still get the following error

--
Error enabling: Error making API request.

URL: POST http://localhost:8200/v1/sys/mounts/op
Code: 400. Errors:

* invalid backend version: 2 errors occurred:
	* Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
	* Unrecognized remote plugin message: 

This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.

 --

The error indicates an out of date SDK / protocol is being used

**Comment by datagen24** [comment]
Adding when attempting to build with SDK past 0.4.1 I get the following
error.
--
vendor/github.com/hashicorp/go-secure-stdlib/parseutil/parseutil.go:453:36: undefined: math.MinInt
vendor/github.com/hashicorp/go-secure-stdlib/parseutil/parseutil.go:453:49: undefined: math.MaxInt
vendor/github.com/hashicorp/go-secure-stdlib/parseutil/parseutil.go:491:41: undefined: math.MinInt
vendor/github.com/hashicorp/go-secure-stdlib/parseutil/parseutil.go:491:54: undefined: math.MaxInt
--

I am not a programer, but I am a sysadmin security nut so fixing this is beyond me, more than happy to help

**Comment by ag-adampike** [comment]
Hi @datagen24!

I believe this is a duplicate of #18. The actual issue is incorrect instructions when writing the configuration (see https://github.com/1Password/vault-plugin-secrets-onepassword/issues/18#issuecomment-1384375021 and https://github.com/1Password/vault-plugin-secrets-onepassword/issues/18#issuecomment-1414582104)

If you start over with the pinned SDK version, it should work using the correct `op/` path:

```
vault write op/config @op-connect-config.json
```

I've tested this recently and it works on the latest version of Vault server. I'm submitting a PR shortly that will contain corrected instructions. :-)
